spring:
    cloud:
        gateway:
            routes:
                - id: fetch_uuid
                  uri: http://localhost:80/
                  predicates:
                      - Path=/uuid

                - id: response_header_get
                  uri: http://localhost:80/
                  predicates:
                      - Path=/response-headers
                      - Method=GET

                - id: response_header_post
                  uri: http://localhost:80/
                  predicates:
                      - Path=/response-headers
                      - Method=POST

management:
    endpoints:
        web:
            exposure:
                include:
                    - gateway
                    - health
                    - info
    endpoint:
        health:
            show-details: always
            show-components: always

logging:
    level:
        org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
