spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda:
    bpm:
        admin-user:
            id: demo
            password: demo
        auto-deployment-enabled: false

server:
    port: 8081

spring:
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:mem:camunda;DB_CLOSE_ON_EXIT=FALSE
        driverClassName: org.h2.Driver
        username: sa
        password:
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
